account_id = "95e065d2e3f..."
name = "docs-site-api"
type = "webpack"
workers_dev = false
webpack_config = "webpack.config.js"

[site]
bucket = "./public"
entry-point = "./workers-site"

# Production
[env.production]
name = "docs-site"
route = "https://developers.cloudflare.com/api*"
zone_id = "351cf9fc660523187714fa772ad5ca49"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"

# Staging
[env.staging]
account_id = "95e06..."
name = "staging"
zone_id = "8703d409.."
route = "https://staging.bigfluffycloudflare.com/api*"

